### ISSUE TITLE
更新Node版本

### ISSUE THREAD

**Issue by AdingApkgg** [HCLonely/live2dNodeApi#2]
Vercel部署似乎出现了问题？
请更新NodeJS版本
![image](https://github.com/HCLonely/live2dNodeApi/assets/119665355/d1f825b7-5925-44ff-a2d1-b395d0ac3202)
![image](https://github.com/HCLonely/live2dNodeApi/assets/119665355/54806f3b-5433-445d-94ea-c62ab5c2fab1)

**Comment by HCLonely** [comment]
已修复
